"""Frozen coreloop binding generated by scripts/vendor_coreloop.py."""

from . import core_loop as pystruct
from . import core_loop_errors as errors
from . import lusee_appIds as appids
from . import lusee_commands as commands

# Compatibility aliases retained for existing uncrater callers.
_errors = errors
appId = appids
command = commands

command_from_value = {
    value: name
    for name, value in vars(commands).items()
    if not name.startswith("_") and isinstance(value, int)
}
value_from_command = {name: value for value, name in command_from_value.items()}

appId_from_value = {
    value: name
    for name, value in vars(appids).items()
    if name.startswith("AppID_") and isinstance(value, int)
}
value_from_appId = {name: value for value, name in appId_from_value.items()}

error_bits = {1 << bit: "RESERVED" for bit in range(32)}
for name, value in vars(errors).items():
    if isinstance(value, int) and value in error_bits:
        error_bits[value] = name

value_from_format = {
    name: getattr(pystruct, name)
    for name in dir(pystruct)
    if name.startswith("OUTPUT_")
}
format_from_value = {value: name for name, value in value_from_format.items()}

__all__ = [
    "appId",
    "appId_from_value",
    "appids",
    "command",
    "command_from_value",
    "commands",
    "error_bits",
    "errors",
    "format_from_value",
    "pystruct",
    "value_from_appId",
    "value_from_command",
    "value_from_format",
]
