#!/usr/bin/env python3
"""Vendor frozen coreloop ctypes schemas from exact local Git commits."""

from __future__ import annotations

import argparse
from collections.abc import Mapping
import ctypes
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CORELOOP = REPO_ROOT.parent / "coreloop"
PROVENANCE_PATH = REPO_ROOT / "uncrater" / "coreloop" / "provenance.json"
EXPECTED_CTYPESGEN_VERSION = "1.1.1"

PINNED_BINDINGS = {
    "203": {
        "canonical_schema_id": 0x203,
        "accepted_reported_versions": [0x203],
        "variant": None,
        "source_release": "2r03",
        "source_commit": "798da926b6c4af0ea410ddf0c4191cb15fbcf9e3",
        "signatures": [],
    },
    "305": {
        "canonical_schema_id": 0x305,
        "accepted_reported_versions": [0x305],
        "variant": None,
        "source_release": "3r05",
        "source_commit": "9355df3c89055cee84b6fee69dbfcd199487e0aa",
        "signatures": [],
    },
    "306-early": {
        "canonical_schema_id": 0x306,
        "accepted_reported_versions": [0x306],
        "variant": "early",
        "source_release": "3r06-early",
        "source_commit": "9e8db56c0e723968d2c01c26f32bf727a1a7a014",
        "signatures": [
            {"appid": 0x206, "payload_length": 2571, "housekeeping_type": 0},
            {"appid": 0x280, "payload_length": 590},
        ],
    },
    "306-final": {
        "canonical_schema_id": 0x306,
        "accepted_reported_versions": [0x306],
        "variant": "final",
        "source_release": "3r06-final",
        "source_commit": "bb016489adb1d209e36fec814d928e38454aa5d4",
        "signatures": [
            {"appid": 0x206, "payload_length": 2692, "housekeeping_type": 0},
            {"appid": 0x206, "payload_length": 90, "housekeeping_type": 100},
            {"appid": 0x206, "payload_length": 48, "housekeeping_type": 101},
            {"appid": 0x280, "payload_length": 597},
        ],
    },
    "307": {
        "canonical_schema_id": 0x307,
        "accepted_reported_versions": [0x307],
        "variant": None,
        "source_release": "3r09",
        "source_commit": "38770b94bd20dfdbf52d1d8b872a716537b851f3",
        "signatures": [],
    },
}

SOURCE_INPUTS = (
    "documentation/lusee_appIds.md",
    "documentation/lusee_commands.md",
    "documentation/toplevel_commands.md",
    "scripts/create_appid_include.py",
    "scripts/create_cmd_include.py",
    "coreloop/core_loop.h",
    "coreloop/calibrator.h",
    "coreloop/spectrometer_interface.h",
    "coreloop/core_loop_errors.h",
    "coreloop/flash_interface.h",
    "pycoreloop/Makefile",
)

# ctypesgen follows quoted includes while parsing core_loop.h. Keep the fixed
# list above for the documented inputs, and also discover local includes so a
# future packed helper header cannot silently escape provenance hashing.
HEADER_ENTRY_POINTS = (
    "coreloop/core_loop.h",
    "coreloop/calibrator.h",
    "coreloop/spectrometer_interface.h",
    "coreloop/core_loop_errors.h",
)

GENERATED_SOURCE_OUTPUTS = (
    "coreloop/lusee_appIds.h",
    "coreloop/lusee_commands.h",
    "pycoreloop/lusee_appIds.py",
    "pycoreloop/lusee_commands.py",
)

BUNDLE_OUTPUTS = (
    "__init__.py",
    "core_loop.py",
    "core_loop_errors.py",
    "lusee_appIds.py",
    "lusee_commands.py",
)

ABI_STRUCT_NAMES = (
    "ADC_stat",
    "calibrator_state",
    "calibrator_stats",
    "calibrator_error_reg",
    "calibrator_errors",
    "calibrator_metadata",
    "route_state",
    "time_counters",
    "core_state_base",
    "cdi_stats",
    "delayed_cdi_sending",
    "watchdog_state",
    "watchdog_config",
    "watchdog_packet",
    "core_state",
    "saved_core_state",
    "saved_calibrator_weights",
    "saved_state",
    "state_recover_notification",
    "end_of_sequence",
    "startup_hello",
    "heartbeat",
    "waveform_metadata",
    "meta_data",
    "housekeeping_data_base",
    "housekeeping_data_0",
    "housekeeping_data_1",
    "housekeeping_data_2",
    "housekeeping_data_3",
    "housekeeping_data_100",
    "housekeeping_data_101",
    "flash_copy_report_t",
)

UINT64_FIELDS = {
    ("ADC_stat", "sumv"),
    ("ADC_stat", "sumv2"),
    ("time_counters", "heartbeat_counter"),
    ("time_counters", "resettle_counter"),
    ("time_counters", "cdi_wait_counter"),
    ("time_counters", "cdi_dispatch_counter"),
    ("core_state_base", "uC_time"),
    ("cdi_stats", "cdi_bytes_sent"),
    ("watchdog_packet", "uC_time"),
    ("waveform_metadata", "timestamp"),
}

BUNDLE_INIT = '''"""Frozen coreloop binding generated by scripts/vendor_coreloop.py."""

from . import core_loop as pystruct
from . import core_loop_errors as errors
from . import lusee_appIds as appids
from . import lusee_commands as commands

# Compatibility aliases retained for existing uncrater callers.
_errors = errors
appId = appids
command = commands

command_from_value = {
    value: name
    for name, value in vars(commands).items()
    if not name.startswith("_") and isinstance(value, int)
}
value_from_command = {name: value for value, name in command_from_value.items()}

appId_from_value = {
    value: name
    for name, value in vars(appids).items()
    if name.startswith("AppID_") and isinstance(value, int)
}
value_from_appId = {name: value for value, name in appId_from_value.items()}

error_bits = {1 << bit: "RESERVED" for bit in range(32)}
for name, value in vars(errors).items():
    if isinstance(value, int) and value in error_bits:
        error_bits[value] = name

value_from_format = {
    name: getattr(pystruct, name)
    for name in dir(pystruct)
    if name.startswith("OUTPUT_")
}
format_from_value = {value: name for name, value in value_from_format.items()}

__all__ = [
    "appId",
    "appId_from_value",
    "appids",
    "command",
    "command_from_value",
    "commands",
    "error_bits",
    "errors",
    "format_from_value",
    "pystruct",
    "value_from_appId",
    "value_from_command",
    "value_from_format",
]
'''


class VendorError(RuntimeError):
    """Raised when source provenance or generated ABI validation fails."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sha256_json(value: Any) -> str:
    data = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(data).hexdigest()


def transitive_local_headers(source_root: Path) -> tuple[str, ...]:
    """Return quoted headers reachable from the ctypesgen entry points."""

    pending = list(HEADER_ENTRY_POINTS)
    found: set[str] = set()
    include_pattern = re.compile(r'^\s*#\s*include\s+"([^"]+)"')
    while pending:
        relative = pending.pop()
        if relative in found:
            continue
        path = source_root / relative
        if not path.is_file():
            raise VendorError(f"Missing vendoring input {relative}")
        found.add(relative)
        for line in path.read_text(encoding="utf-8").splitlines():
            match = include_pattern.match(line)
            if match is None:
                continue
            included = match.group(1)
            candidates = (
                path.parent / included,
                source_root / "coreloop" / included,
            )
            for candidate in candidates:
                if candidate.is_file():
                    pending.append(candidate.relative_to(source_root).as_posix())
                    break
            else:
                raise VendorError(
                    f"Cannot resolve local include {included!r} from {relative}"
                )
    return tuple(sorted(found))


def source_input_paths(source_root: Path) -> tuple[str, ...]:
    """Return every fixed and transitively included authoritative input."""

    return tuple(sorted({*SOURCE_INPUTS, *transitive_local_headers(source_root)}))


def run_checked(
    command: list[str],
    *,
    cwd: Path | None = None,
    allow_stderr: bool = False,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode:
        raise VendorError(
            f"Command failed ({result.returncode}): {' '.join(command)}\n"
            f"{result.stdout}{result.stderr}"
        )
    if result.stderr and not allow_stderr:
        raise VendorError(
            f"Command emitted unexpected stderr: {' '.join(command)}\n{result.stderr}"
        )
    return result


def ctypesgen_distribution_version(executable: str) -> str:
    """Return the distribution version used by the selected console script."""

    located = shutil.which(executable)
    path = Path(located if located is not None else executable)
    try:
        with path.resolve(strict=True).open("rb") as stream:
            first_line = stream.readline(4096)
    except OSError as exc:
        raise VendorError(f"Cannot inspect ctypesgen executable {executable!r}") from exc
    if not first_line.startswith(b"#!"):
        raise VendorError("ctypesgen must be a Python console script with a shebang")
    try:
        interpreter = shlex.split(first_line[2:].decode("utf-8").strip())
    except (UnicodeDecodeError, ValueError) as exc:
        raise VendorError("ctypesgen has an invalid interpreter shebang") from exc
    if not interpreter:
        raise VendorError("ctypesgen has an empty interpreter shebang")
    probe = (
        "from importlib.metadata import version; "
        "print(version('ctypesgen'))"
    )
    version = run_checked([*interpreter, "-c", probe], allow_stderr=True).stdout.strip()
    if version != EXPECTED_CTYPESGEN_VERSION:
        raise VendorError(
            f"ctypesgen {EXPECTED_CTYPESGEN_VERSION} is required, got {version!r}"
        )
    return version


def extract_commit(coreloop_repo: Path, commit: str, destination: Path) -> None:
    resolved = run_checked(
        ["git", "rev-parse", f"{commit}^{{commit}}"], cwd=coreloop_repo
    ).stdout.strip()
    if resolved != commit:
        raise VendorError(f"Expected exact commit {commit}, resolved {resolved}")
    archive = subprocess.run(
        ["git", "archive", "--format=tar", commit],
        cwd=coreloop_repo,
        check=True,
        stdout=subprocess.PIPE,
    ).stdout
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:") as stream:
        destination_resolved = destination.resolve()
        for member in stream.getmembers():
            target = (destination / member.name).resolve()
            if not target.is_relative_to(destination_resolved):
                raise VendorError(f"Unsafe path in git archive: {member.name}")
        if sys.version_info >= (3, 12):
            stream.extractall(destination, filter="data")
        else:
            stream.extractall(destination)


def load_module(path: Path, name: str) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise VendorError(f"Cannot import generated module {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def normalized_ctype(ctype: Any) -> Mapping[str, Any]:
    if isinstance(ctype, type) and issubclass(ctype, ctypes.Array):
        return {
            "kind": "array",
            "length": ctype._length_,
            "size": ctypes.sizeof(ctype),
            "element": normalized_ctype(ctype._type_),
        }
    if isinstance(ctype, type) and issubclass(ctype, ctypes.Structure):
        name = ctype.__name__.removeprefix("struct_")
        return {"kind": "struct", "name": name, "size": ctypes.sizeof(ctype)}
    code = getattr(ctype, "_type_", None)
    if code in ("b", "h", "i", "l", "q"):
        kind, signed = "integer", True
    elif code in ("B", "H", "I", "L", "Q"):
        kind, signed = "integer", False
    elif code == "?":
        kind, signed = "boolean", False
    elif code == "c":
        kind, signed = "character", False
    elif code in ("f", "d"):
        kind, signed = "float", True
    else:
        kind, signed = "opaque", None
    return {
        "kind": kind,
        "signed": signed,
        "size": ctypes.sizeof(ctype),
    }


def canonical_abi(module: Any) -> dict[str, Any]:
    structures: dict[str, Any] = {}
    for name in ABI_STRUCT_NAMES:
        structure = getattr(module, name, None)
        if structure is None:
            structure = getattr(module, f"struct_{name}", None)
        if structure is None:
            continue
        if not isinstance(structure, type) or not issubclass(
            structure, ctypes.Structure
        ):
            raise VendorError(f"Generated symbol {name} is not a ctypes Structure")
        fields = {}
        for field in structure._fields_:
            field_name, field_type = field[:2]
            fields[field_name] = {
                "offset": getattr(structure, field_name).offset,
                "size": ctypes.sizeof(field_type),
                "type": normalized_ctype(field_type),
            }
        structures[name] = {
            "size": ctypes.sizeof(structure),
            "alignment": ctypes.alignment(structure),
            "fields": fields,
        }
    if not structures:
        raise VendorError("No packet ABI structures were generated")
    return structures


def c_probe_source(abi: Mapping[str, Any]) -> str:
    lines = [
        "#include <stddef.h>",
        "#include <stdio.h>",
        '#include "core_loop.h"',
        "int main(void) {",
    ]
    for structure_name, structure in abi.items():
        lines.append(
            f'printf("S\\t{structure_name}\\t%zu\\t%zu\\n", '
            f"sizeof(struct {structure_name}), _Alignof(struct {structure_name}));"
        )
        for field_name in structure["fields"]:
            lines.append(
                f'printf("F\\t{structure_name}\\t{field_name}\\t%zu\\t%zu\\n", '
                f"offsetof(struct {structure_name}, {field_name}), "
                f"sizeof(((struct {structure_name} *)0)->{field_name}));"
            )
    lines.extend(("return 0;", "}"))
    return "\n".join(lines) + "\n"


def compile_c_abi_probe(
    source_root: Path,
    abi: Mapping[str, Any],
    *,
    compiler: str,
) -> dict[str, Any]:
    """Ask the C compiler for every ctypes-visible structure size and offset."""

    with tempfile.TemporaryDirectory(prefix="uncrater-abi-") as directory:
        temporary = Path(directory)
        source = temporary / "abi_probe.c"
        executable = temporary / "abi_probe"
        source.write_text(c_probe_source(abi), encoding="ascii")
        run_checked(
            [
                compiler,
                "-std=c11",
                "-I",
                str(source_root / "coreloop"),
                str(source),
                "-o",
                str(executable),
            ],
            allow_stderr=True,
        )
        output = run_checked([str(executable)]).stdout

    probed: dict[str, Any] = {}
    for line in output.splitlines():
        fields = line.split("\t")
        if fields[0] == "S":
            _, structure_name, size, alignment = fields
            probed[structure_name] = {
                "size": int(size),
                "alignment": int(alignment),
                "fields": {},
            }
        elif fields[0] == "F":
            _, structure_name, field_name, offset, size = fields
            probed[structure_name]["fields"][field_name] = {
                "offset": int(offset),
                "size": int(size),
            }
        else:
            raise VendorError(f"Malformed C ABI probe output: {line}")
    return probed


def validate_c_abi(ctypes_abi: Mapping[str, Any], c_abi: Mapping[str, Any]) -> None:
    if set(ctypes_abi) != set(c_abi):
        raise VendorError("C and ctypes structure sets differ")
    for structure_name, ctypes_structure in ctypes_abi.items():
        c_structure = c_abi[structure_name]
        for attribute in ("size", "alignment"):
            if ctypes_structure[attribute] != c_structure[attribute]:
                raise VendorError(
                    f"ABI mismatch for {structure_name}.{attribute}: "
                    f"ctypes={ctypes_structure[attribute]}, C={c_structure[attribute]}"
                )
        if set(ctypes_structure["fields"]) != set(c_structure["fields"]):
            raise VendorError(f"ABI field set differs for {structure_name}")
        for field_name, ctypes_field in ctypes_structure["fields"].items():
            c_field = c_structure["fields"][field_name]
            for attribute in ("offset", "size"):
                if ctypes_field[attribute] != c_field[attribute]:
                    raise VendorError(
                        f"ABI mismatch for {structure_name}.{field_name}.{attribute}: "
                        f"ctypes={ctypes_field[attribute]}, C={c_field[attribute]}"
                    )
    for structure_name, field_name in UINT64_FIELDS:
        if structure_name not in ctypes_abi:
            continue
        if ctypes_abi[structure_name]["fields"][field_name]["size"] != 8:
            raise VendorError(f"{structure_name}.{field_name} is not eight bytes")


def integer_constants(module: Any, prefix: str) -> dict[str, int]:
    return {
        name: value
        for name, value in vars(module).items()
        if name.startswith(prefix) and isinstance(value, int)
    }


def core_integer_constants(module: Any) -> dict[str, int]:
    """Return decoder-domain integer constants, excluding ctypesgen runtime state."""

    runtime_names = {"DEFAULT_MODE", "SIZEOF_TIME_T"}
    return {
        name: value
        for name, value in vars(module).items()
        if name.isupper()
        and not name.startswith("RTLD_")
        and name not in runtime_names
        and isinstance(value, int)
    }


def c_constants(path: Path, prefix: str) -> dict[str, int]:
    constants = {}
    pattern = re.compile(
        rf"^#define\s+({re.escape(prefix)}[A-Za-z0-9_]*)\s+(0[xX][0-9A-Fa-f]+|[0-9]+)\s*$"
    )
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            constants[match.group(1)] = int(match.group(2), 0)
    return constants


def header_define_names(path: Path) -> tuple[str, ...]:
    names = []
    pattern = re.compile(r"^#define\s+([A-Za-z_][A-Za-z0-9_]*)\b")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match and not match.group(1).endswith("_H"):
            names.append(match.group(1))
    return tuple(names)


def named_integer_constants(module: Any, names: tuple[str, ...]) -> dict[str, int]:
    constants = {}
    missing = []
    for name in names:
        value = getattr(module, name, None)
        if isinstance(value, int):
            constants[name] = value
        else:
            missing.append(name)
    if missing:
        raise VendorError(f"Generated integer constants are missing: {missing}")
    return constants


def semantic_constants(
    core_module: Any,
    appid_module: Any,
    command_module: Any,
    error_module: Any,
    error_names: tuple[str, ...],
) -> dict[str, dict[str, int]]:
    """Collect constants whose values are part of the decoder contract."""

    return {
        "appids": integer_constants(appid_module, "AppID_"),
        "commands": {
            **integer_constants(command_module, "RFS_"),
            **integer_constants(command_module, "CTRL_"),
        },
        "core_constants": core_integer_constants(core_module),
        "errors": named_integer_constants(error_module, error_names),
        "output_formats": integer_constants(core_module, "OUTPUT_"),
    }


def load_bundle_contract(
    bundle: Path,
    binding_key: str,
    error_names: tuple[str, ...],
) -> dict[str, Any]:
    """Load one bundle and reduce host-specific ctypesgen text to semantics."""

    suffix = re.sub(r"[^A-Za-z0-9_]", "_", binding_key)
    core_module = load_module(bundle / "core_loop.py", f"vendor_core_{suffix}")
    appid_module = load_module(bundle / "lusee_appIds.py", f"vendor_appids_{suffix}")
    command_module = load_module(
        bundle / "lusee_commands.py", f"vendor_commands_{suffix}"
    )
    error_module = load_module(
        bundle / "core_loop_errors.py", f"vendor_errors_{suffix}"
    )
    return {
        "version_id": int(core_module.VERSION_ID),
        "abi": canonical_abi(core_module),
        "constants": semantic_constants(
            core_module,
            appid_module,
            command_module,
            error_module,
            error_names,
        ),
    }


def constant_fingerprints(constants: Mapping[str, Any]) -> dict[str, str]:
    """Hash semantic constant groups without storing large tables in provenance."""

    return {name: sha256_json(values) for name, values in constants.items()}


def markdown_appids(path: Path) -> dict[str, int]:
    constants = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        columns = line.split("|")
        if len(columns) < 5:
            continue
        offset, name = (column.strip() for column in columns[1:3])
        if not name.startswith("AppID_"):
            continue
        normalized = offset.lower().replace("x", "0")
        constants[name] = 0x200 + int(normalized, 16)
    return constants


def validate_generated_constants(source_root: Path) -> None:
    appid_module = load_module(
        source_root / "pycoreloop" / "lusee_appIds.py", "vendor_appids"
    )
    appid_python = integer_constants(appid_module, "AppID_")
    appid_c = c_constants(source_root / "coreloop" / "lusee_appIds.h", "AppID_")
    appid_docs = markdown_appids(
        source_root / "documentation" / "lusee_appIds.md"
    )
    if appid_python != appid_c or appid_python != appid_docs:
        raise VendorError("Markdown, C, and Python AppID constants differ")

    command_module = load_module(
        source_root / "pycoreloop" / "lusee_commands.py", "vendor_commands"
    )
    command_python = {
        **integer_constants(command_module, "RFS_"),
        **integer_constants(command_module, "CTRL_"),
    }
    command_c = {
        **c_constants(source_root / "coreloop" / "lusee_commands.h", "RFS_"),
        **c_constants(source_root / "coreloop" / "lusee_commands.h", "CTRL_"),
    }
    if command_python != command_c:
        raise VendorError("Generated C and Python command constants differ")


def normalize_generated_python(path: Path, source_root: Path) -> None:
    text = path.read_text(encoding="utf-8")
    text = text.replace(f"{source_root}/", "")
    normalized = "\n".join(line.rstrip() for line in text.splitlines()).rstrip() + "\n"
    path.write_text(normalized, encoding="utf-8")


def generate_binding(
    binding_key: str,
    source_root: Path,
    *,
    ctypesgen: str,
    compiler: str,
) -> tuple[dict[str, Any], Path, dict[str, Any], tuple[str, ...]]:
    pin = PINNED_BINDINGS[binding_key]
    source_hashes = {
        path: sha256_file(source_root / path)
        for path in source_input_paths(source_root)
    }

    run_checked([sys.executable, "scripts/create_appid_include.py"], cwd=source_root)
    run_checked([sys.executable, "scripts/create_cmd_include.py"], cwd=source_root)
    validate_generated_constants(source_root)

    # The coreloop Makefile has incomplete header dependencies. Regenerate in
    # the extracted commit every time instead of trusting an incremental build.
    bundle = source_root / "uncrater_bundle"
    bundle.mkdir()
    generated_core = bundle / "core_loop.py"
    generated_errors = bundle / "core_loop_errors.py"
    run_checked(
        [
            ctypesgen,
            str(source_root / "coreloop" / "core_loop.h"),
            str(source_root / "coreloop" / "calibrator.h"),
            "-o",
            str(generated_core),
        ],
        allow_stderr=True,
    )
    run_checked(
        [
            ctypesgen,
            str(source_root / "coreloop" / "core_loop_errors.h"),
            "-o",
            str(generated_errors),
        ],
        allow_stderr=True,
    )
    shutil.copyfile(
        source_root / "pycoreloop" / "lusee_appIds.py",
        bundle / "lusee_appIds.py",
    )
    shutil.copyfile(
        source_root / "pycoreloop" / "lusee_commands.py",
        bundle / "lusee_commands.py",
    )
    (bundle / "__init__.py").write_text(BUNDLE_INIT, encoding="ascii")
    for name in BUNDLE_OUTPUTS:
        normalize_generated_python(bundle / name, source_root)

    error_names = header_define_names(
        source_root / "coreloop" / "core_loop_errors.h"
    )
    contract = load_bundle_contract(bundle, binding_key, error_names)
    if contract["version_id"] != pin["canonical_schema_id"]:
        raise VendorError(
            f"{binding_key} generated VERSION_ID 0x{contract['version_id']:X}, expected "
            f"0x{pin['canonical_schema_id']:X}"
        )
    ctypes_abi = contract["abi"]
    c_abi = compile_c_abi_probe(source_root, ctypes_abi, compiler=compiler)
    validate_c_abi(ctypes_abi, c_abi)

    generated_source_hashes = {
        path: sha256_file(source_root / path) for path in GENERATED_SOURCE_OUTPUTS
    }
    bundle_hashes = {path: sha256_file(bundle / path) for path in BUNDLE_OUTPUTS}
    ctypesgen_version = ctypesgen_distribution_version(ctypesgen)
    record = {
        **pin,
        "source_files": source_hashes,
        "generated_source_files": generated_source_hashes,
        "generated_files": bundle_hashes,
        "semantic_fingerprints": constant_fingerprints(contract["constants"]),
        "generation": {
            "ctypesgen_command": [
                "ctypesgen",
                "coreloop/core_loop.h",
                "coreloop/calibrator.h",
            ],
            "ctypesgen_error_command": [
                "ctypesgen",
                "coreloop/core_loop_errors.h",
            ],
            "ctypesgen_version": ctypesgen_version,
            "vendor_script": "scripts/vendor_coreloop.py",
        },
        # The detailed ABI is reproducibly recomputed from pystruct. Keeping
        # only its fingerprint avoids a 10,000-line provenance manifest.
        "abi": {"sha256": sha256_json(ctypes_abi)},
    }
    return record, bundle, contract, error_names


def destination_for(binding_key: str) -> Path:
    suffix = binding_key.replace("-", "_")
    return REPO_ROOT / "uncrater" / "coreloop" / f"pycoreloop_{suffix}"


def check_existing_bundle(
    binding_key: str,
    record: Mapping[str, Any],
    generated_contract: Mapping[str, Any],
    error_names: tuple[str, ...],
    provenance: Mapping[str, Any],
) -> None:
    destination = destination_for(binding_key)
    if not destination.is_dir():
        raise VendorError(f"Missing vendored binding directory {destination}")
    missing = [name for name in BUNDLE_OUTPUTS if not (destination / name).is_file()]
    if missing:
        raise VendorError(f"Vendored binding {binding_key} is missing {missing}")

    # ctypesgen embeds host paths and chooses host aliases for fixed-width C
    # types. Compare the actual packet contract, not generated source text.
    existing_contract = load_bundle_contract(destination, binding_key, error_names)
    for contract_part in ("version_id", "abi", "constants"):
        if existing_contract[contract_part] != generated_contract[contract_part]:
            raise VendorError(
                f"Vendored {contract_part} is stale for binding {binding_key}"
            )

    expected = provenance["bindings"].get(binding_key)
    if expected is None:
        raise VendorError(f"Missing provenance record for {binding_key}")
    if set(expected) != set(record):
        raise VendorError(f"Provenance fields differ for binding {binding_key}")
    for key in (
        "canonical_schema_id",
        "accepted_reported_versions",
        "variant",
        "source_release",
        "source_commit",
        "signatures",
        "source_files",
        "generated_source_files",
        "generated_files",
        "semantic_fingerprints",
        "generation",
        "abi",
    ):
        if key == "generated_files":
            continue
        if expected.get(key) != record.get(key):
            raise VendorError(f"Provenance mismatch for {binding_key}.{key}")
    current_hashes = {
        name: sha256_file(destination / name) for name in BUNDLE_OUTPUTS
    }
    if expected["generated_files"] != current_hashes:
        raise VendorError(f"Vendored output hashes differ for {binding_key}")
    if expected["abi"]["sha256"] != sha256_json(existing_contract["abi"]):
        raise VendorError(f"Vendored ABI fingerprint differs for {binding_key}")
    if expected["semantic_fingerprints"] != constant_fingerprints(
        existing_contract["constants"]
    ):
        raise VendorError(f"Vendored constant fingerprints differ for {binding_key}")


def install_bundle(
    binding_key: str,
    generated: Path,
    generated_contract: Mapping[str, Any],
    error_names: tuple[str, ...],
) -> dict[str, str]:
    destination = destination_for(binding_key)
    if all((destination / name).is_file() for name in BUNDLE_OUTPUTS):
        existing_contract = load_bundle_contract(destination, binding_key, error_names)
        if existing_contract == generated_contract:
            # A frozen schema is content-addressed by semantics. Preserve its
            # existing generated text when only ctypesgen host output differs.
            return {
                name: sha256_file(destination / name) for name in BUNDLE_OUTPUTS
            }
    destination.mkdir(parents=True, exist_ok=True)
    for name in BUNDLE_OUTPUTS:
        shutil.copyfile(generated / name, destination / name)
    return {name: sha256_file(destination / name) for name in BUNDLE_OUTPUTS}


def load_existing_provenance() -> dict[str, Any]:
    if not PROVENANCE_PATH.exists():
        return {"format_version": 1, "bindings": {}}
    return json.loads(PROVENANCE_PATH.read_text(encoding="utf-8"))


def vendor(
    coreloop_repo: Path,
    binding_keys: list[str],
    *,
    ctypesgen: str,
    compiler: str,
    check: bool,
) -> None:
    provenance = load_existing_provenance()
    provenance.setdefault("format_version", 1)
    provenance.setdefault("bindings", {})
    if check:
        if set(provenance) != {"format_version", "bindings"}:
            raise VendorError("Provenance must contain only format_version and bindings")
        if provenance["format_version"] != 1:
            raise VendorError("Unsupported provenance format version")
        if set(binding_keys) == set(PINNED_BINDINGS) and set(
            provenance["bindings"]
        ) != set(PINNED_BINDINGS):
            raise VendorError("Provenance binding set differs from the pinned bindings")

    for binding_key in binding_keys:
        pin = PINNED_BINDINGS[binding_key]
        with tempfile.TemporaryDirectory(
            prefix=f"uncrater-vendor-{binding_key}-"
        ) as directory:
            source_root = Path(directory)
            extract_commit(coreloop_repo, pin["source_commit"], source_root)
            record, generated, generated_contract, error_names = generate_binding(
                binding_key,
                source_root,
                ctypesgen=ctypesgen,
                compiler=compiler,
            )
            if check:
                check_existing_bundle(
                    binding_key,
                    record,
                    generated_contract,
                    error_names,
                    provenance,
                )
            else:
                record["generated_files"] = install_bundle(
                    binding_key,
                    generated,
                    generated_contract,
                    error_names,
                )
                provenance["bindings"][binding_key] = record

    if not check:
        serialized = json.dumps(provenance, indent=2, sort_keys=True) + "\n"
        PROVENANCE_PATH.write_text(serialized, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--coreloop",
        type=Path,
        default=DEFAULT_CORELOOP,
        help="local coreloop Git checkout containing every pinned commit",
    )
    parser.add_argument(
        "--binding",
        action="append",
        choices=tuple(PINNED_BINDINGS),
        help="binding to vendor; repeat as needed (default: all)",
    )
    parser.add_argument(
        "--ctypesgen",
        default=shutil.which("ctypesgen"),
        help="ctypesgen executable",
    )
    parser.add_argument("--compiler", default=shutil.which("cc"), help="C compiler")
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate and validate without writing repository files",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.ctypesgen is None:
        raise VendorError("ctypesgen is required; install the vendor extra")
    if args.compiler is None:
        raise VendorError("A C compiler is required for ABI validation")
    coreloop_repo = args.coreloop.resolve()
    if not (coreloop_repo / ".git").exists():
        raise VendorError(f"Not a coreloop Git checkout: {coreloop_repo}")
    binding_keys = args.binding or list(PINNED_BINDINGS)
    vendor(
        coreloop_repo,
        binding_keys,
        ctypesgen=args.ctypesgen,
        compiler=args.compiler,
        check=args.check,
    )
    mode = "verified" if args.check else "vendored"
    print(f"{mode} bindings: {', '.join(binding_keys)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
